### ISSUE TITLE
Strings with slashes are displayed incorrectly in Interactive

### ISSUE THREAD

**Issue by hmemcpy** [fsprojects/atom-fsharp#101]
![image](https://cloud.githubusercontent.com/assets/601206/8776137/86f4ee06-2ef7-11e5-9a14-de5467b0b4a2.png)

**Comment by forki** [comment]
![bug](https://cloud.githubusercontent.com/assets/57396/8776191/775bdbce-2eef-11e5-9197-76b1028b221b.gif)

**Comment by Krzysztof-Cieslak** [comment]
Should be fixed in `0.8.2`

**Comment by hmemcpy** [comment]
Better :)
![image](https://cloud.githubusercontent.com/assets/601206/8848669/c3d1b57e-3141-11e5-92ca-b772f28ab351.png)

But maybe it should be `c:\\dev\\console` on Windows?

**Comment by Krzysztof-Cieslak** [comment]
@hmemcpy: Suggested format used in `0.8.3`

**Comment by hmemcpy** [comment]
More slashes!!!1
Thank you :)
