### ISSUE TITLE
Odd Error Underlining From Linter 

### ISSUE THREAD

**Issue by cloudRoutine** [fsprojects/atom-fsharp#105]
![](http://i.imgur.com/1vsZBfs.png)

On the bottom it says there are no issues.

When I close and reopen the file it's fine

![](http://i.imgur.com/xbp4y1o.png)

But then when I start editing the file again it has error underlining that persists

![](http://i.imgur.com/UsGAEQt.png)

**Comment by Krzysztof-Cieslak** [comment]
Yep, I have similar reproduction on my machine. I guess it's some problem with [Linter plugin](https://github.com/atom-community/linter), please report issue there.

**Comment by cloudRoutine** [comment]
submitted  https://github.com/atom-community/linter/issues/808

**Comment by Krzysztof-Cieslak** [comment]
Fixed by guys from Linter plugin
