### ISSUE TITLE
Possible enhancement: Smart suggestions for F# code completion list

### ISSUE THREAD

**Issue by mfalda** [fsprojects/atom-fsharp#106]
Since F# has a strong type system it would be nice to suggest at the top of the code completion list the values that are the most relevant for the context of the current code, like in [Netbeans Smart Suggestions] (https://netbeans.org/kb/73/java/editor-codereference.html#codecompletion).

For example, given the following definitions:

```F#
let a = 4
let b = 5
let c = a * b
let d = 3.7
let e = "a"

let f (x: int) = // infer f :: int -> float
float x / 2.0
```

when trying to complete the expression

```F#
printfn "%f"
```

the list should first suggest "d" or "f", according to the desired format.

Once opted for "f", the next list should prioritize "a", "b" or "c" for the expression

```F#
printfn "%f" f
```

I do not know if this idea would weaken the inference engine of F# (for example the user could have make a mistake in the "printfn" format and this system would confirm his error).

I have fist proposed this idea to the [VisualStudio User voice](https://visualstudio.uservoice.com/forums/121579-visual-studio/suggestions/8706280-smart-suggestions-for-f-code-completion-list%29) without success, so far.

**Comment by Krzysztof-Cieslak** [comment]
That's actually interesting idea but I have no idea if F# language services allows on something like that. /cc: @7sharp9 @rneatherway

**Comment by 7sharp9** [comment]
Topological sort based on parent / context.  Topo sort based on parent is in my TODO list, I don't think its strictly relevant for FCS as its just a post sort.  FCS already does its own sorting and removal of certain completion items.

**Comment by rneatherway** [comment]
@mfalda that is a very cool idea. Determining the context is important for such a feature, and not always straightforward though. I think this should probably be an issue over at FSharp.Compiler.Service.

**Comment by mfalda** [comment]
Thank you, so I could try to post this idea to the FSharp.Compiler.Service (it appears to me that @7sharp9 is somewhat involved in that project). In fact, by enhancing FCS also other editors, like for example the humble SciTE, could be enriched. I think that a possible implementation would combine a Typed Abstract Syntax Tree parsing ([TAST](http://fsharp.github.io/FSharp.Compiler.Service/typedtree.html)) with a list of annotated symbols. To be continued elsewhere...

**Comment by Krzysztof-Cieslak** [comment]
OK, So I'll close this issue - to be reopened when it gets implemented in FSAC / FSC.

Please create issue for it on FSharp.Compiler.Service as suggested by @rneatherway

**Comment by 7sharp9** [comment]
I'm not entirely sure it's an FCS feature, I suppose a sort type union could be supplied when using GetSymbolDeclarations to either sort in the current sorted fashion or another type.  The current sort is first pre filtered removing operators and duplicate constructor definitions then sorted by type and number of generic parameters.     Remembering that declaration can stem from contexts differing from global to dotted types.

**Comment by mfalda** [comment]
Before writing to FCS I want to show you a simple script I have made:

```F#
#r "FSharp.Compiler.Service.dll"

open System
open System.IO
open Microsoft.FSharp.Compiler.SourceCodeServices
open Microsoft.FSharp.Compiler


// Create an interactive checker instance
let checker = FSharpChecker.Create()

// Split the input & define file name
let filename = "smart_compl.fsx" // my example script
let inputLines = File.ReadAllText filename

let projOptions =
    checker.GetProjectOptionsFromScript(filename, inputLines)
    |> Async.RunSynchronously

// Perform parsing and checking
let parseResults, checkFileAnswer =
    checker.ParseAndCheckFileInProject (filename, 0, inputLines, projOptions)
    |> Async.RunSynchronously

let checkFileResults =
    match checkFileAnswer with
    | FSharpCheckFileAnswer.Succeeded(res) -> res
    | res -> failwithf "Parsing did not finish... (%A)" res

let partialAssemblySignature = checkFileResults.PartialAssemblySignature

let moduleEntity = partialAssemblySignature.Entities.[0]
for fnVal in moduleEntity.MembersFunctionsAndValues do
    printfn "%A (%A)" fnVal fnVal.FullType // (or  fnVal.FullType.TypeDefinition.DisplayName to match with the tooltips signatures)

// Get tool tip at the specified location (??)
let tip = checkFileResults.GetToolTipTextAlternate(10, 18, inputLines, ["f"], 0)
printfn "%A" tip
```

whose output is
```
val a (type Microsoft.FSharp.Core.int)
val b (type Microsoft.FSharp.Core.int)
val c (type Microsoft.FSharp.Core.int)
val d (type Microsoft.FSharp.Core.float)
val e (type Microsoft.FSharp.Core.string)
val f (type Microsoft.FSharp.Core.int -> Microsoft.FSharp.Core.float)
Microsoft.FSharp.Control.FSharpAsync`1[Microsoft.FSharp.Compiler.SourceCodeServices.FSharpToolTipText]
```

I am not able to get the tooltip value, however in this script I have obtained a list of typed declarations that could be filtered according to the signature of the function near the cursor ("f" in the example, that is "val f: x:int ->float", easily parseable). I do not know neither how printf-like functions could be analyzed (they do not have an explicit signature in tooltips) nor whether there are other cases to be taken into account. Just an idea.

**Comment by 7sharp9** [comment]
This is actually parameter completion for partial functions, this is not supported anywhere at present, only tuple type parameter hinting and completion is currently supported.

I was talking about general completion lists which can occur on space, dot and forced by CTRL SPACE.  Parameter completion is currently only triggered on a `(` or `< `afaik.  Having them trigger on an arbitrary space is must more difficult and would mean parsing the current context of the caret.  It could also be computationally expensive.  Speed is one of the big issues currently FCS is pretty slow as is.

**Comment by 7sharp9** [comment]
In the case of a completion on:
```
printfn "%f" §
```
You would have to evaluate `printfn "%f" to find the type, and then filter the declaration list by the inferred type.  Getting the excat context of what expression or subexpression to partially apply could be quite tricky i.e.
```
  let complex a b c d =
    string (float (a + float32 c) / b) + d
```

`printfn "%s" complex 1.f §`
