### ISSUE TITLE
Not working at all on Win 10

### ISSUE THREAD

**Issue by essenciary** [fsprojects/atom-fsharp#110]
I'm probably missing something obvious but I can't get it to work on Win 10 at all.
I have installed both Visual Studio 2015 and Mono and I've added fsi, fsc and Mono/bin to the PATH. They work just fine in a terminal. Also, I've configured the path to Mono in the plugin settings (C:\Program Files (x86)\Mono\bin)
I have installed node, npm, yeoman and the f# generator. 

However, the plugin doesn't seem to do anything. The expected behavior (per my Mac setup) is that upon opening the FSI tab the plugin outputs the welcome message from the mono fsharpi: 

    F# Interactive for F# 3.1 (Open Source Edition)
    Freely distributed under the Apache 2.0 Open Source License
    
    For help type #help;;
    
    >

Instead, I get an empty text area. 
Also, upon sending content to the FSI tab to be evaluated, nothing happens. 
Finally, it seems that the code itself doesn't get validated in the editor (no errors are being displayed). 

Thanks!

**Comment by essenciary** [comment]
Mmm... might be a bigger issue related to node-gyp on win x64. The elixir REPL is broken too, the install failing with a node-gyp build error.

**Comment by Krzysztof-Cieslak** [comment]
At the moment, `atom-fsharp` on Windows requires having [F# 3.1](http://www.microsoft.com/en-us/download/details.aspx?id=44011) and [MSBuild 12](https://www.microsoft.com/en-us/download/details.aspx?id=40760) installed. ( Or Visual Studio 2013). I think `FsAutoComplete` got updated to support VS2015-only Windows installations but it may take few days for me to update `atom-fsharp`, so best way at the moment is installing those 2 tools.

**Comment by essenciary** [comment]
Thanks @Krzysztof-Cieslak I'll give it a try and follow up.

**Comment by essenciary** [comment]
@Krzysztof-Cieslak got it working by installing the 2 pieces of software. Many thanks for your support!
