### ISSUE TITLE
Getting "position is out of range" for almost everything

### ISSUE THREAD

**Issue by tpetricek** [fsprojects/atom-fsharp#111]
I just installed the latest version of Atom (1.0.7) with the latest version of the F# plugin (0.12.0) on Mac and it looks like the IntelliSense is often broken - the error I see in the developer console is "Position out of range". The FsAutoComplete process starts and runs fine and F# Interactive is working too.

### Detailed information

I type the following:

    open System
    let rnd = new Random()
    rnd

I put mouse pointer over `System`, this works (I get a tooltip as expected) - the developer console shows:
 
    tooltip "/Users/tomas/Temp/test.fsx" 1 11

I put mouse pointer over `rnd` on the last line, but nothing happens. The console shows:

    tooltip "/Users/tomas/Temp/test.fsx" 3 2
    { "Kind": "error", "Data":"Position is out of range" }

When I type dot on the first line after `System`, I also get no completion:

    completion "/Users/tomas/Temp/test.fsx" 1 13 filter
    { "Kind": "error", "Data":"Position is out of range" }

Could there be something wrong in the new version of FsAutoComplete? /cc @rneatherway
In the meantime, is there an easy way to install and older version of a package?

**Comment by Krzysztof-Cieslak** [comment]
Well, actually that's weird - I have absolutely no idea with snippet You've given. I haven't also noticed any problems after last update of FSAC (we are still on `0.21.1` FSAC) (well, FSAC tends to hang for few seconds from time to time but it's for sure not this case - I've experienced it only on decent size projects). Those errors suggest that file is not parsed while You type code, are there `parse` requests logged in the console?
![1](https://cloud.githubusercontent.com/assets/5427083/9305273/6a6261ba-44f0-11e5-9501-c2fff424399e.gif)

**Comment by Krzysztof-Cieslak** [comment]
And for second part of - yes, it's possible to install past version of plugin using `apm install <package_name>@<package_version>` command from command line / terminal. I guess it requires uninstalling current version of plugin. For more info use `apm help install`

**Comment by tpetricek** [comment]
Do you think this could be because Mac uses different newlines? (I'll dig deeper to see what's going on...)

**Comment by Krzysztof-Cieslak** [comment]
My 1st idea is some problem with parse request - check if there are logged `parse` request and if they return any result. I guess that if problem was with Mac newlines someone would report it earlier.

**Comment by tpetricek** [comment]
You're probably right - there is something wrong with the parsing. The `FSharpIDE.provideErrors` function is called to create the linter, but I never see the `lint` function actually being called.

Do I need some other plugin that uses this and triggers linting?

**Comment by tpetricek** [comment]
![rtfm-you-must 1](https://cloud.githubusercontent.com/assets/485413/9318962/16243f82-4541-11e5-8db3-ce63e72a62fa.jpg)

**Comment by tpetricek** [comment]
Installing linter fixed the issue, but I'm not sure if providing the updated source code to the editor when the linter is triggered is often enough - when I was playing with this on my (slow) Mac, it would occasionally happen that I had to wait quite a bit of time before the linter decided to run (and until then, I would not get any auto-completion).

In the web editor I did for www.fun3d.net, we always passed the latest version of the full text when issuing any command, which seems to be working fast enough.

**Comment by rneatherway** [comment]
> In the web editor I did for www.fun3d.net, we always passed the latest version of the full text when issuing any command, which seems to be working fast enough.

This is what I do in emacs (as well as an on-idle parse to get up to date errors).

**Comment by Krzysztof-Cieslak** [comment]
Linter (so `parse` request) should be called every-time user stops editing file for few milliseconds so I guess state of FSAC should be up to date every time something else is requested. I've used to make `parse` request more often ( before most commands) but from what I've experienced, FSAC had some performance problems with too many requests (actually, still I sometimes need to wait few seconds since FSAC is not keeping up with number of send requests - I feel I'll need to dig in more into FSAC and try finding bottlenecks)

On the other hand - it's very important to have up-to-date autocomplete (more than stuff like tooltips, quickinfo etc where user can wait a moment to get up-to-date result), so I might agree that for it it's necessary to make `parse` request before.

**Comment by tpetricek** [comment]
I agree - there is a big difference between the following two (assuming we're getting auto-completion at `$`):

    rnd $
    rnd.$

... and you could get this if the linter does not trigger the parsing after just one key press. Agreed on tooltips though - those do not need the most up-to-date state anyway and there is a delay before you move the mouse..

**Comment by Krzysztof-Cieslak** [comment]
OK, forcing `parse` before autocomplete included in new release (`0.12.1`)
