### ISSUE TITLE
Hide error info tooltip while intellisense is active

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsprojects/atom-fsharp#114]
![image](https://cloud.githubusercontent.com/assets/873919/9424214/9f74eecc-48ec-11e5-8709-1f741cc064a8.png)

**Comment by Krzysztof-Cieslak** [comment]
I don't think that I have lot of control over it - it's behavior of both 2 different plugins used - autocomplete and linter. I just provide service for both their plugins and don't have direct control over it.

**Comment by vasily-kirichenko** [comment]
That's very sad to hear :( If it's completely impossible to fix, I don't mind if you close this issue.

**Comment by Krzysztof-Cieslak** [comment]
Well, it's just JS, CSS and HTML under the hood so *everything* is possible. But I don't see any "stable" way of doing it right now, so I'll close it.

Maybe will come back to it in the future
