### ISSUE TITLE
Intellisense's signature tooltip disappears

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsprojects/atom-fsharp#115]
![6677](https://cloud.githubusercontent.com/assets/873919/9424225/4c752f42-48ed-11e5-844e-cebbd468a319.gif)

**Comment by vasily-kirichenko** [comment]
That's very sad to hear :( If it's completely impossible to fix, I don't mind if you close this issue.

**Comment by Krzysztof-Cieslak** [comment]
Fixed in `0.12.7`
