### ISSUE TITLE
Quick info panel tries to show the second line of long info

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsprojects/atom-fsharp#117]
![6677](https://cloud.githubusercontent.com/assets/873919/9424248/3eccc188-48ee-11e5-9dcf-254d673dd57c.gif)

**Comment by Krzysztof-Cieslak** [comment]
How it's solved in VFPT? Should I just used one top line (in presented case it ends before "Full name" part)

**Comment by vasily-kirichenko** [comment]
We just join all tooltip lines (with some post processing, like adding ` .` in front of camel cased words, if they are at the head of line and the like). It think the problem is that a small top part of the second line of the panel is visible.

**Comment by Krzysztof-Cieslak** [comment]
As for now, I've decided to just use one top line from returned information. In most cases it provides enough information (type / function parameters / etc.). Additional information ( full name, xml doc etc.) can be obtained by using tooltip.

Released in `0.12.6`
