### ISSUE TITLE
Colorization with multi-line comments

### ISSUE THREAD

**Issue by mathias-brandewinder** [fsprojects/atom-fsharp#124]
In an fsx file, typing 
```
(*
*)
let x = 42
```
... grays out / italicizes all the text below, as if it was all comments. This seems to happen as soon as the closing block is alone. For instance,
```
(*
This works *)
```
but
```
(* This does not work
*)
```

**Comment by Krzysztof-Cieslak** [comment]
Fixed in `0.12.10`
