### ISSUE TITLE
A lot of false positive errors on a fsx file

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsprojects/atom-fsharp#31]
![image](https://cloud.githubusercontent.com/assets/873919/7525020/b7b6eecc-f50e-11e4-8b13-44f6d92c901d.png)

1. Preprocessor directive handled in a very wrong way.
2. Something very wrong with 'to' "token".
3. Line number (202) is not correct.

**Comment by Krzysztof-Cieslak** [comment]
Is it possible to upload whole file or You can't do that?

**Comment by Krzysztof-Cieslak** [comment]
Or at least smallest file recreating issue.

**Comment by vasily-kirichenko** [comment]
https://github.com/fsprojects/VisualFSharpPowerTools/blob/master/build.fsx

**Comment by Krzysztof-Cieslak** [comment]
Looks like I can't recreate issue. 

![image](https://cloud.githubusercontent.com/assets/5427083/7532589/e3f8cb22-f568-11e4-9769-8bcb36f73f9c.png)


Can You try opening file again or using `Ctrl + Alt + R` (views |> reload)?

**Comment by forki** [comment]
I saw the same as @vasily-kirichenko - maybe it's something with install.

**Comment by Krzysztof-Cieslak** [comment]
Well, I've tested it on both my local version and version installed through Atom, still can't reproduce error :(

**Comment by Krzysztof-Cieslak** [comment]
Hey, maybe it's connected with lack of `DLL` files referenced by the `fsx` file? I've got similar issues after opening some freshly cloned repos with it before downloading dependencies using Paket / NuGet
