### ISSUE TITLE
Uncaught Error: This socket is closed.

### ISSUE THREAD

**Issue by alexandru** [fsprojects/atom-fsharp#47]
I just installed the package.

**Atom Version**: 0.199.0
**System**: linux 3.16.0-37-generic
**Thrown From**: [FSharp](https://github.com/fsprojects/FSharp.Atom) package, v0.2.5

### Stack Trace

Uncaught Error: This socket is closed.

```
At events.js:141

Error: This socket is closed.
  at Socket._writeGeneric (net.js:634:19)
  at Socket._write (net.js:687:8)
  at doWrite (_stream_writable.js:295:12)
  at writeOrBuffer (_stream_writable.js:282:5)
  at Socket.Writable.write (_stream_writable.js:210:11)
  at Socket.write (net.js:612:40)
  at /home/alex/.atom/packages/FSharp/lib/fsharp.js:1211:18
  at Option__Iterate$ChildProcess_ChildProcess_ (/home/alex/.atom/packages/FSharp/lib/fsharp.js:1542:14)
  at LanguageService__ask$ (/home/alex/.atom/packages/FSharp/lib/fsharp.js:1191:12)
  at LanguageService__parse$ (/home/alex/.atom/packages/FSharp/lib/fsharp.js:1260:12)
  at LanguageService__parseEditor$ (/home/alex/.atom/packages/FSharp/lib/fsharp.js:1300:14)
  at FSharpIDE__initialize$ (/home/alex/.atom/packages/FSharp/lib/fsharp.js:1022:5)
  at /home/alex/.atom/packages/FSharp/lib/fsharp.js:962:14

```

### Commands

```
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
FSharp, v0.2.5
atom-yeoman, v0.2.0
language-fsharp, v0.8.4
linter, v0.12.2

# Dev
No dev packages
```

**Comment by Krzysztof-Cieslak** [comment]
Should be fixed in `0.2.8`

**Comment by alexandru** [comment]
Doesn't seem to happen anymore, thanks @Krzysztof-Cieslak

**Comment by 7sharp9** [comment]
I get this with FSI:send selection

**Comment by devboy** [comment]
Also get this on FSI:send

**Comment by xelibrion** [comment]
Versions 0.7.2 and 0.8.0 seem to have the same issue on my Mac OS X
> 'mono' could not be spawned. Is it installed and on your path? If so please open an issue on the package spawning the process.

And I definitely have mono in the PATH

> xelibrion@mbp13:~$ mono -V
Mono JIT compiler version 4.0.1 (tarball Fri Jun  5 13:22:30 PDT 2015)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           normal
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	LLVM:          supported, not enabled.
	GC:            sgen

**Comment by 7sharp9** [comment]
Afaik atom does not capture the path variable on OS X

**Comment by xelibrion** [comment]
The plugin version 0.6.1 used to work just fine - not sure what have changed.

**Comment by Krzysztof-Cieslak** [comment]
@xelibrion, does it happen on startup or when you try to do anything particular?

**Comment by xelibrion** [comment]
@Krzysztof-Cieslak yes, I get those message when I open the editor - and what makes it worse is the fact and I'm no longer able to open `*.fsx` files without uninstalling the plugin.

**Comment by xelibrion** [comment]
It seems there is a problem with the way atom captures environment variables - everything works fine if atom is launched from the terminal, but things start going sideways if launched from dock, there was similar issue raised in OmniSharp repository https://github.com/OmniSharp/omnisharp-atom/issues/42

**Comment by Krzysztof-Cieslak** [comment]
@xelibrion: OK, that sounds interesting - can You check if it's plugin problem or Atom problem? For example reverse to plugin version You know that was working well and check if it's working on current Atom version.

**Comment by 7sharp9** [comment]
I don't think atom can use environmental variables when not launched from the terminal.

**Comment by xelibrion** [comment]
@Krzysztof-Cieslak I confirm that current version of the plugin is working when atom is launched from the terminal. I've also noticed the other day that rolling back the version of the plugin doesn't really help anymore - the core issue being that atom was launched from the dock.

Should there be a setting where users could specify the full path to mono?

**Comment by TonyAbell** [comment]
I am getting this issue to on Win7.  I am working on production a sample which will repo the error.

**Comment by Krzysztof-Cieslak** [comment]
@xelibrion: In newest release (`0.10.1`) there is option to set up mono path in plugin settings. Setting it should fix problem.

**Comment by xelibrion** [comment]
@Krzysztof-Cieslak awesome, thanks for that!
