### ISSUE TITLE
Consider renaming

### ISSUE THREAD

**Issue by dsyme** [fsprojects/atom-fsharp#50]
Hi all,

There is a suggestion (by me) to add a recommendation to http://fsharp.github.io/2014/09/19/fsharp-libraries.html that names like "FSharp.*" be only used for libraries (rather than tools or editor addins).

This came up in a discussion about splitting the "fsharpbinding" repo, where names like "FSharp.Emacs" were suggested, but instead we chose "emacs-fsharp-mode". 

Anyway, I just wanted to mention this and offer the suggestion that this project be renamed, e.g. to "atom-fsharp-addin" or the like, i.e. following the idiomatic naming for Atom addins.

This isn't urgent, it's just something I wanted to put on the table.

Best regards
Don

**Comment by Krzysztof-Cieslak** [comment]
Hello Don,

I don't see any problem with renaming, I would also want to retain consistency between all Atom plugins we create, (as for now it's only Paket but I guess also FAKE support will be separated to own plugin).

@forki, Any views / ideas for naming style?

**Comment by dsyme** [comment]
Looking at https://github.com/atom it seems that "language-fsharp" would be the natural name, though I think for sanity we'd need "atom" there too, so "atom-language-fsharp" or "atom-fsharp" may be best.

**Comment by dsyme** [comment]
BTW after the fsharpbinding repo got split most F# editing projects are at http://github.com/fsharp.  It's possible it might be more consistent to move this project there, though I don't have strong opinions either way.

**Comment by tpetricek** [comment]
"language-fsharp" is the name of the syntax highlighting.

"autocomplete-fsharp" would make more sense for this project (following other autocomplete projects) though it is not really covering all that this plugin does - so perhaps "intellisense-fsharp" (or with the prefix "atom-intellisense-fsharp")?

**Comment by dsyme** [comment]
(FWIW the comparison with "Paket.Atom" naming may not be the right way to think about this - I would like to see ``FSharp.XYZ`` names used for libraries, namespaces and packages, rather than tools and editor addins.  Paket doesn't have this same aim for ``Paket.XYZ`` names.)

**Comment by rodrigovidal** [comment]
I think we should follow the TypeScript's TypeStrong community and use atom-fsharp

https://github.com/TypeStrong/atom-typescript

**Comment by Krzysztof-Cieslak** [comment]
I'm not aware of any guidelines or conventions for Atom plugins (for example, TypeScript plugin is called `atom-typescript`, Haskell one is `ide-haskell`). Name format `language-XXX` is used for plugins adding only syntax highlighting while this plugin provides more features.

Considering that other plugins are called `vim-fsharp`, `emacs-fsharp-mode`, and `sublime-fsharp-package` I think that `atom-fsharp` should be good name.

**Comment by dsyme** [comment]
+1

**Comment by Krzysztof-Cieslak** [comment]
OK, so I renamed both repository and plugin name in Atom Package Manager to `atom-fsharp`.
Sorry for using bad name in the first place :)

I think we can close this issue.

**Comment by dsyme** [comment]
Great, thanks!
