### ISSUE TITLE
Single-line comments incorrectly highlighted when *) present

### ISSUE THREAD

**Issue by rneatherway** [fsprojects/atom-fsharp#58]
Originally reported by @latkin at https://github.com/fsharp/fsharpbinding/issues/882

When `*)` is present in a single-line `//` comment, that comment line gets colored incorrectly.

```fsharp
// here is a normal comment
// here is a busted *) comment 
```

**Comment by Krzysztof-Cieslak** [comment]
Fixed in `0.11.0`
