### ISSUE TITLE
Cursor Position Issue for Intellisense Tooltips

### ISSUE THREAD

**Issue by cloudRoutine** [fsprojects/atom-fsharp#60]
The mapping of cursor position to symbol seems to be off by a column or two

![](http://i.imgur.com/22umTEz.png)

![](http://i.imgur.com/sFSSDgN.png)

![](http://i.imgur.com/NMVycXk.png)

**Comment by Krzysztof-Cieslak** [comment]
Look's like more general problem with Atom coordinates translation. https://github.com/atom/atom/issues/7193

**Comment by Krzysztof-Cieslak** [comment]
I've pushed temporary fix for it, waiting for Atom team response on underlying problem
