### ISSUE TITLE
Another Odd Cursor Position Issue

### ISSUE THREAD

**Issue by cloudRoutine** [fsprojects/atom-fsharp#62]
The Cursor always appears over the first window instead of the active one

![](http://i.imgur.com/Lq79Yy9.png)

![](http://i.imgur.com/FuX99dB.png)

But not just on duplicates, on different files too.

![](http://i.imgur.com/aQHROfT.png)

**Comment by Krzysztof-Cieslak** [comment]
Should be fixed in `0.5.6`
