### ISSUE TITLE
FSI:Send-Selection shortcut not working on OSX

### ISSUE THREAD

**Issue by krontogiannis** [fsprojects/atom-fsharp#79]
Hello,

it seems that the 'alt-enter' shortcut doesn't send the selection to FSI, but deletes the selection and insert a new line instead. That happens in OSX, in Windows there is no problem.

Output from the key binding resolver:
![atom-fsi](https://cloud.githubusercontent.com/assets/2443933/8351125/95f59676-1b33-11e5-95b2-2e99d9abb7a7.png)

**Comment by krontogiannis** [comment]
Also, out of curiosity, why is the 'send-line' mapped to alt-/ instead of alt-' (like in Visual Studio)? Is there any technical reason or just personal preference?

**Comment by Krzysztof-Cieslak** [comment]
It was just my personal preference - it should be easy to change in Atom settings If You don't like it :)
