### ISSUE TITLE
Can't install the plugin at all

### ISSUE THREAD

**Issue by abjrcode** [fsprojects/atom-fsharp#83]
Whenever I try to install the package via Atom settings view it hangs. I tried to do this via **apm** directly with the `--verbose` option and it doesn't work too, it blocks indefinitely.
Here is the output of the command:
>  
apm install atom-fsharp --verbose
REQUEST { method: 'GET',
  url: 'https://atom.io/api/packages/atom-fsharp',
  json: true,
  retries: 4,
  proxy: null,
  strictSSL: true,
  headers: { 'User-Agent': 'npm/2.5.1 node/v0.10.35 win32 ia32' },
  uri: null,
  callback: [Function] }
REQUEST make request https://atom.io/api/packages/atom-fsharp
REQUEST onRequestResponse https://atom.io/api/packages/atom-fsharp 200 { server:
 'Cowboy',
  connection: 'close',
  date: 'Mon, 29 Jun 2015 17:43:56 GMT',
  status: '200 OK',
  'strict-transport-security': 'max-age=631152000',
  'x-frame-options': 'DENY',
  'x-xss-protection': '1; mode=block',
  'x-content-type-options': 'nosniff',
  'content-security-policy': 'default-src \'self\'; connect-src \'self\'; font-s
rc \'self\'; frame-src \'self\' https://www.youtube.com; img-src https://* \'sel
f\' data:; media-src \'none\'; object-src \'self\'; script-src \'self\' \'unsafe
-inline\' https://ssl.google-analytics.com https://www.google-analytics.com http
s://platform.twitter.com; style-src \'self\' \'unsafe-inline\';',
  'content-type': 'application/json; charset=utf-8',
  etag: '"9f7e4cf7afdccf5c825df3ea2cc768cd"',
  'cache-control': 'max-age=0, private, must-revalidate',
  'x-request-id': '78b2f89d-9694-4648-832b-c6b975932fd2',
  'x-runtime': '0.093537',
  'x-rack-cache': 'miss',
  via: '1.1 vegur' }
REQUEST finish init function https://atom.io/api/packages/atom-fsharp
REQUEST response end https://atom.io/api/packages/atom-fsharp 200 { server: 'Cow
boy',
  connection: 'close',
  date: 'Mon, 29 Jun 2015 17:43:56 GMT',
  status: '200 OK',
  'strict-transport-security': 'max-age=631152000',
  'x-frame-options': 'DENY',
  'x-xss-protection': '1; mode=block',
  'x-content-type-options': 'nosniff',
  'content-security-policy': 'default-src \'self\'; connect-src \'self\'; font-s
rc \'self\'; frame-src \'self\' https://www.youtube.com; img-src https://* \'sel
f\' data:; media-src \'none\'; object-src \'self\'; script-src \'self\' \'unsafe
-inline\' https://ssl.google-analytics.com https://www.google-analytics.com http
s://platform.twitter.com; style-src \'self\' \'unsafe-inline\';',
  'content-type': 'application/json; charset=utf-8',
  etag: '"9f7e4cf7afdccf5c825df3ea2cc768cd"',
  'cache-control': 'max-age=0, private, must-revalidate',
  'x-request-id': '78b2f89d-9694-4648-832b-c6b975932fd2',
  'x-runtime': '0.093537',
  'x-rack-cache': 'miss',
  via: '1.1 vegur' }
REQUEST end event https://atom.io/api/packages/atom-fsharp
REQUEST has body https://atom.io/api/packages/atom-fsharp 28439
REQUEST emitting complete https://atom.io/api/packages/atom-fsharp
REQUEST { method: 'GET',
  url: 'https://www.atom.io/api/packages/atom-fsharp/versions/0.6.2/tarball',
  proxy: null,
  strictSSL: true,
  headers: { 'User-Agent': 'npm/2.5.1 node/v0.10.35 win32 ia32' },
  uri: null,
  callback: undefined }
REQUEST make request https://www.atom.io/api/packages/atom-fsharp/versions/0.6.2
/tarball
REQUEST onRequestResponse https://www.atom.io/api/packages/atom-fsharp/versions/
0.6.2/tarball 302 { server: 'Cowboy',
  connection: 'close',
  date: 'Mon, 29 Jun 2015 17:43:59 GMT',
  status: '302 Found',
  'strict-transport-security': 'max-age=631152000',
  'x-frame-options': 'DENY',
  'x-xss-protection': '1; mode=block',
  'x-content-type-options': 'nosniff',
  'content-security-policy': 'default-src \'self\'; connect-src \'self\'; font-s
rc \'self\'; frame-src \'self\' https://www.youtube.com; img-src https://* \'sel
f\' data:; media-src \'none\'; object-src \'self\'; script-src \'self\' \'unsafe
-inline\' https://ssl.google-analytics.com https://www.google-analytics.com http
s://platform.twitter.com; style-src \'self\' \'unsafe-inline\';',
  location: 'https://codeload.github.com/fsprojects/atom-fsharp/legacy.tar.gz/v0
.6.2',
  'content-type': 'text/html; charset=utf-8',
  'cache-control': 'no-cache',
  'x-request-id': '1e389f11-8945-4727-96c2-4a992c967712',
  'x-runtime': '0.074822',
  'x-rack-cache': 'miss',
  via: '1.1 vegur' }
REQUEST redirect https://codeload.github.com/fsprojects/atom-fsharp/legacy.tar.g
z/v0.6.2
REQUEST redirect to https://codeload.github.com/fsprojects/atom-fsharp/legacy.ta
r.gz/v0.6.2
REQUEST {}
REQUEST make request https://codeload.github.com/fsprojects/atom-fsharp/legacy.t
ar.gz/v0.6.2
REQUEST response end https://codeload.github.com/fsprojects/atom-fsharp/legacy.t
ar.gz/v0.6.2 302 { server: 'Cowboy',
  connection: 'close',
  date: 'Mon, 29 Jun 2015 17:43:59 GMT',
  status: '302 Found',
  'strict-transport-security': 'max-age=631152000',
  'x-frame-options': 'DENY',
  'x-xss-protection': '1; mode=block',
  'x-content-type-options': 'nosniff',
  'content-security-policy': 'default-src \'self\'; connect-src \'self\'; font-s
rc \'self\'; frame-src \'self\' https://www.youtube.com; img-src https://* \'sel
f\' data:; media-src \'none\'; object-src \'self\'; script-src \'self\' \'unsafe
-inline\' https://ssl.google-analytics.com https://www.google-analytics.com http
s://platform.twitter.com; style-src \'self\' \'unsafe-inline\';',
  location: 'https://codeload.github.com/fsprojects/atom-fsharp/legacy.tar.gz/v0
.6.2',
  'content-type': 'text/html; charset=utf-8',
  'cache-control': 'no-cache',
  'x-request-id': '1e389f11-8945-4727-96c2-4a992c967712',
  'x-runtime': '0.074822',
  'x-rack-cache': 'miss',
  via: '1.1 vegur' }
REQUEST onRequestResponse https://codeload.github.com/fsprojects/atom-fsharp/leg
acy.tar.gz/v0.6.2 200 { 'content-length': '4417803',
  'access-control-allow-origin': 'https://render.githubusercontent.com',
  'content-security-policy': 'default-src \'none\'',
  'x-xss-protection': '1; mode=block',
  'x-frame-options': 'deny',
  'x-content-type-options': 'nosniff',
  'strict-transport-security': 'max-age=31536000',
  vary: 'Authorization,Accept-Encoding',
  etag: '"c06e1e714058d09d89941e31a5edf0a625e15c4a"',
  'content-type': 'application/x-gzip',
  'content-disposition': 'attachment; filename=fsprojects-atom-fsharp-v0.6.2-0-g
c06e1e7.tar.gz',
  date: 'Mon, 29 Jun 2015 17:44:01 GMT' }
REQUEST finish init function https://codeload.github.com/fsprojects/atom-fsharp/
legacy.tar.gz/v0.6.2

**Comment by Krzysztof-Cieslak** [comment]
Actually, I have no idea what causes this problem. As a workaround You can download [latest release](https://github.com/fsprojects/atom-fsharp/archive/v0.6.2.tar.gz) and by hand extract it to Your atom packages directory (for Mac it's something like `\users\USERNAME\.atom\packages` )

**Comment by abjrcode** [comment]
@Krzysztof-Cieslak I downloaded the latest package and extracted that to the packages folder and now when I open Atom if says the package threw an exception because the JQuery module wasn't found.

**Comment by Krzysztof-Cieslak** [comment]
Try running `npm install` from `\users\USERNAME\.atom\packages\atom-fsharp`

**Comment by abjrcode** [comment]
@Krzysztof-Cieslak Thank you. Everything works just fine now. I thing this was a problem with the network which now just works !.

**Comment by ptrelford** [comment]
I encountered a similar stack trace inside an "enterprise" environment. 
I was able to install following @Krzysztof-Cieslak's instructions above getting the latest bits from the project's GH releases https://github.com/ionide/ionide-fsharp/releases (thanks @Krzysztof-Cieslak).
You may also need to run ``npm install``, and before you do that you may need to install node & npm, which can be found here: https://iojs.org/en/
