### ISSUE TITLE
Project file not parsed when file in sub-folder is opened

### ISSUE THREAD

**Issue by rojepp** [fsprojects/atom-fsharp#88]
For instance, when I do `atom -d .` in my atom-fsharp dev dir, atom will typically open up 
with a file that is not in project root folder. Nothing works then, you get compilation errors etc. 
To make atom-fsharp 'get it', I have to open a file in the project root, which makes it find the fsproj file. 

To fix this, directories will need to be searched recursively going upward from current file, about [here](https://github.com/fsprojects/atom-fsharp/blob/develop/src/Components/Parser.fs#L33).

**Comment by Krzysztof-Cieslak** [comment]
#89 merged and released as part of `0.6.4`
