### ISSUE TITLE
No way to minimise or close the warnings/errors status bar on osx

### ISSUE THREAD

**Issue by 7sharp9** [fsprojects/atom-fsharp#95]
This is on osx.
![screen shot 2015-07-14 at 10 08 21](https://cloud.githubusercontent.com/assets/588746/8669907/4fec6d08-2a10-11e5-8ad4-f5b5aa2607d8.png)

Perhaps provide a way to turn it off via a command too.

**Comment by Krzysztof-Cieslak** [comment]
There was a way of minimizing panel - by toggling off both buttons ( File and Project) in the status bar. Not working tight now due to bug in Linter plugin - https://github.com/AtomLinter/Linter/issues/722

**Comment by Krzysztof-Cieslak** [comment]
Also, there is Linter:TogglePanel command which should turn panel off

**Comment by Krzysztof-Cieslak** [comment]
Fixed in new version of Linter plugin.
