### ISSUE TITLE
internal error: BuildFrameworkTcImports:no resolution of 'FSharp.Core.dll'

### ISSUE THREAD

**Issue by alfonsogarciacaro** [fsprojects/atom-fsharp#97]
Hi there!

I can edit .fsx files without any problem with my laptop (Windows 8.1), but if I try to open a .fs file from a project created by the generator or VS, I get the following errors:
```
internal error: BuildFrameworkTcImports:no resolution of 'FSharp.Core.dll'
Unable to find the file 'FSharp.Core.dll' in any of c:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0 c:\temp\fsharp\console c:\Program Files (x86)\Microsoft SDKs\F#\3.1\Framework\v4.0
```
Indeed, `FSharp.Core.dll` is not in any of these directories, but in `C:\Program Files (x86)\Reference Assemblies\Microsoft\FSharp\.NETFramework\v4.0\4.3.1.0`. How can I tell the plugin where to search?

In my desktop (also Windows 8.1) this problem is not happening when I open F# projects created with VS, even if `FSharp.Core.dll` is actually in the same folder as in the laptop.

Cheers,
Alfonso

**Comment by theor** [comment]
Same problem here !

**Comment by theor** [comment]
had to mklink /J v4.0 v4.5.1 in C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework to fix it. fun.

**Comment by theor** [comment]
Actually, still have the same error...

**Comment by Krzysztof-Cieslak** [comment]
I guess that's some problem connected with FsAutoComplete. //cc: @rneatherway

**Comment by rneatherway** [comment]
This is some kind of issue with FSharp.Compiler.Service. It's really hard for me to debug because I don't have a Windows 8 machine or even one with VS2015. Is it possible to give some more information?

1. dump the full communication log between Atom and FsAutoComplete,
2. What versions of VS, .NET and F# are installed,
3. Post the project file in question

**Comment by alfonsogarciacaro** [comment]
Hi Robin!

I'm posting the info you're asking here. I hope it can help you:

### Visual Studio
* C:\Program Files (x86)\Microsoft Visual Studio 12.0
* C:\Program Files (x86)\Microsoft Visual Studio 14.0

> Both are Community Edition. There are also a remnant of VS 11.0

### .NET
* C:\Windows\Microsoft.NET\Framework\v4.0.30319

### F#
* C:\Program Files (x86)\Reference Assemblies\Microsoft\FSharp\.NETFramework\v2.0\2.3.0.0
* C:\Program Files (x86)\Reference Assemblies\Microsoft\FSharp\.NETFramework\v4.0\4.3.0.0
* C:\Program Files (x86)\Reference Assemblies\Microsoft\FSharp\.NETFramework\v4.0\4.3.1.0
* C:\Program Files (x86)\Reference Assemblies\Microsoft\FSharp\.NETFramework\v4.0\4.4.0.0

> When I type `fsc --version` in the console I get `Microsoft (R) F# Compiler version 12.0.30815.0`

### F# project file
I posted it [here](https://gist.github.com/alfonsogarciacaro/63c092e0c5255accf3d6). I generated it with yeoman fsharp generator, but I have the same error with projects created by VS too.

### Communication log between Atom and FsAutoComplete
I'm not sure if this is what you need, but this is what I got from Atom's debug console when opening console.fsproj first and then console.fs.

```
project "C:\temp\fsharp\console\console.fsproj"

C:\Users\Alfonso\.atom\packages\atom-fsharp\lib\fsharp.js:804 Fsharp_project Wed Jul 22 2015 21:29:18 GMT+0200 (Hora de verano romance) {"Kind":"project","Data":{"Project":"C:\\temp\\fsharp\\console\\console.fsproj","Files":["C:\\temp\\fsharp\\console\\console.fs"],"Output":"console.exe","References":[],"Framework":"v4.5"}}
C:\Users\Alfonso\.atom\packages\atom-fsharp\lib\fsharp.js:804 Fsharp_status Wed Jul 22 2015 21:29:18 GMT+0200 (Hora de verano romance) Ready
C:\Users\Alfonso\.atom\packages\atom-fsharp\lib\fsharp.js:1873 parse "C:\temp\fsharp\console\console.fs"
module console

[<EntryPoint>]
let main argv =
    printfn "%A" argv
    0 // return an integer exit code

<<EOF>>

C:\Users\Alfonso\.atom\packages\atom-fsharp\lib\fsharp.js:1873 project "C:\temp\fsharp\console\console.fsproj"

C:\Users\Alfonso\.atom\packages\atom-fsharp\lib\fsharp.js:804 Fsharp_project Wed Jul 22 2015 21:29:22 GMT+0200 (Hora de verano romance) {"Kind":"project","Data":{"Project":"C:\\temp\\fsharp\\console\\console.fsproj","Files":["C:\\temp\\fsharp\\console\\console.fs"],"Output":"console.exe","References":[],"Framework":"v4.5"}}
C:\Users\Alfonso\.atom\packages\atom-fsharp\lib\fsharp.js:804 Fsharp_status Wed Jul 22 2015 21:29:22 GMT+0200 (Hora de verano romance) Ready
C:\Users\Alfonso\.atom\packages\atom-fsharp\lib\fsharp.js:1873 parse "C:\temp\fsharp\console\console.fs"
module console

[<EntryPoint>]
let main argv =
    printfn "%A" argv
    0 // return an integer exit code

<<EOF>>

C:\Users\Alfonso\.atom\packages\atom-fsharp\lib\fsharp.js:1873 parse "C:\temp\fsharp\console\console.fs"
module console

[<EntryPoint>]
let main argv =
    printfn "%A" argv
    0 // return an integer exit code

<<EOF>>

C:\Users\Alfonso\.atom\packages\atom-fsharp\lib\fsharp.js:1873 parse "C:\temp\fsharp\console\console.fs"
module console

[<EntryPoint>]
let main argv =
    printfn "%A" argv
    0 // return an integer exit code

<<EOF>>

C:\Users\Alfonso\.atom\packages\atom-fsharp\lib\fsharp.js:800 Fsharp_errors Wed Jul 22 2015 21:29:23 GMT+0200 (Hora de verano romance) Object {Kind: "errors", Data: Array[2]}Data: Array[2]0: ObjectEndColumn: 81EndLine: 1FileName: "startup"Message: "internal error: BuildFrameworkTcImports: no resolution of 'FSharp.Core.dll'"Severity: "Error"StartColumn: 1StartLine: 1Subcategory: "typecheck"__proto__: Object1: Objectlength: 2__proto__: Array[0]Kind: "errors"__proto__: Object
C:\Users\Alfonso\.atom\packages\atom-fsharp\lib\fsharp.js:800 Fsharp_errors Wed Jul 22 2015 21:29:23 GMT+0200 (Hora de verano romance) Object {Kind: "errors", Data: Array[2]}
C:\Users\Alfonso\.atom\packages\atom-fsharp\lib\fsharp.js:800 Fsharp_errors Wed Jul 22 2015 21:29:23 GMT+0200 (Hora de verano romance) Object {Kind: "errors", Data: Array[2]}
C:\Users\Alfonso\.atom\packages\atom-fsharp\lib\fsharp.js:800 Fsharp_errors Wed Jul 22 2015 21:29:23 GMT+0200 (Hora de verano romance) Object {Kind: "errors", Data: Array[2]}

C:\Users\Alfonso\.atom\packages\atom-fsharp\lib\fsharp.js:1873 tooltip "C:\temp\fsharp\console\console.fs" 5 16

C:\Users\Alfonso\.atom\packages\atom-fsharp\lib\fsharp.js:1873 tooltip "C:\temp\fsharp\console\console.fs" 5 16

C:\Users\Alfonso\.atom\packages\atom-fsharp\lib\fsharp.js:1873 symboluse "C:\temp\fsharp\console\console.fs" 5 16

C:\Users\Alfonso\.atom\packages\atom-fsharp\lib\fsharp.js:804 Fsharp_error Wed Jul 22 2015 21:29:24 GMT+0200 (Hora de verano romance) {"Kind":"ERROR","Data":"No symbols found"}
```

Please tell me if you need anything else. Thanks a lot for your help, Robin!

**Comment by rneatherway** [comment]
Thanks, this is perfect. From the debug log I can see that FSharp.Compiler.Service is returning no references for your project, which should definitely have mscorlib and FSharp.Core, along with others. This kind of silent failure mode is quite surprising. Is it possible for you to clone the FSharp.Compiler.Service repository and run the tests from that? It would also be very useful if you could try to obtain the detailed log output following: https://fsharp.github.io/FSharp.Compiler.Service/project.html#Cracking-a-project-file

**Comment by alfonsogarciacaro** [comment]
Perfect! This will probably have to wait till the weekend, but I'll do it (I had already forked `FSharp.Compiler.Service` so it shouldn't be a problem)  and report back to you.

Cheers!

**Comment by rneatherway** [comment]
I remembered the previous issue that I think is related: https://github.com/fsharp/FSharp.Compiler.Service/issues/379

The other reporter had a failure mode where an exception was thrown though, which is more what I would expect.

**Comment by alfonsogarciacaro** [comment]
Hi Robin! Sorry for taking son long to reply. In the last version of atom-fsharp this error is not happening any more so apparently it's been fixed somehow :) Closing the issue.

Cheers!
